
--=====================================
--代碼檔
--=====================================
CREATE TABLE CFG_CODETYPE (
    OID            VARCHAR(32) NOT NULL,
    LOCALE         VARCHAR(5)  NOT NULL,
    CodeType       VARCHAR(32) NOT NULL,
    CODEVALUE      VARCHAR(32) NOT NULL,
    CODEDESC       VARCHAR(300) ,
    CODEORDER      INTEGER,
    PTYPE          VARCHAR(32),
    PVALUE         VARCHAR(32),
    UPDATER   VARCHAR(10) ,
    UPDATETIME TIMESTAMP 
);

COMMENT ON TABLE CFG_CODETYPE IS '共用代碼檔';

CREATE UNIQUE INDEX XCodeType01 ON CFG_CODETYPE (
	LOCALE ASC, 
	CodeType ASC, 
	CODEVALUE ASC
);

COMMENT ON COLUMN CFG_CODETYPE.oid IS 'Object ID';
COMMENT ON COLUMN CFG_CODETYPE.codeType IS '代碼類型';
COMMENT ON COLUMN CFG_CODETYPE.codeValue IS '代碼值';
COMMENT ON COLUMN CFG_CODETYPE.codeDesc IS '代碼說明';
COMMENT ON COLUMN CFG_CODETYPE.locale IS '語言別';
COMMENT ON COLUMN CFG_CODETYPE.codeOrder IS '代碼順序';
COMMENT ON COLUMN CFG_CODETYPE.UPDATER IS '最後修改人';
COMMENT ON COLUMN CFG_CODETYPE.UPDATETIME IS '最後修改時間';

--ALTER TABLE CFG_CODETYPE ADD PTYPE VARCHAR(32);
--ALTER TABLE CFG_CODETYPE ADD PVALUE VARCHAR(32);