-- *********************************
-- 錯誤代碼表
-- *********************************

--DROP TABLE CFG_ERRORCODE;

CREATE TABLE CFG_ERRORCODE (
 OID             VARCHAR(32) NOT NULL,
 CODE   VARCHAR(20) NOT NULL,
 LOCALE   VARCHAR(5) NOT NULL,
 SEVERITY  VARCHAR(5) NOT NULL,
 MESSAGE   VARCHAR(1024) NOT NULL,
 SUGGESTION  VARCHAR(1024) ,
 SYSID        VARCHAR(5),
 SENDMON         CHAR(1)     DEFAULT 'N',
 HELPURL        VARCHAR(128) ,
 LASTMODIFYBY VARCHAR(10) NOT NULL,
 LASTMODIFYTIME TIMESTAMP NOT NULL,
 CONSTRAINT P_CFG_ERRORCODE PRIMARY KEY (OID)
);

CREATE UNIQUE INDEX XERRORCODE01
    ON CFG_ERRORCODE (CODE ASC, LOCALE ASC);
    
COMMENT ON TABLE CFG_ERRORCODE IS '錯誤代碼表';    

COMMENT ON COLUMN CFG_ERRORCODE.OID IS 'OID';
COMMENT ON COLUMN CFG_ERRORCODE.CODE IS '狀況代碼';
COMMENT ON COLUMN CFG_ERRORCODE.LOCALE IS '語言別(zh_TW/zh_CN/en)';
COMMENT ON COLUMN CFG_ERRORCODE.SEVERITY IS '等級(INFO/ERROR/WARN/NA)';
COMMENT ON COLUMN CFG_ERRORCODE.MESSAGE IS '狀況說明';
COMMENT ON COLUMN CFG_ERRORCODE.SUGGESTION IS '建議處理方式';
COMMENT ON COLUMN CFG_ERRORCODE.SYSID IS '系統別';
COMMENT ON COLUMN CFG_ERRORCODE.SENDMON IS '是否送監控(Y/N)';
COMMENT ON COLUMN CFG_ERRORCODE.HELPURL IS 'HELP URL';
COMMENT ON COLUMN CFG_ERRORCODE.LASTMODIFYBY IS '最後修改人';
COMMENT ON COLUMN CFG_ERRORCODE.LASTMODIFYTIME IS '最後修改時間';